kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: documents
  labels:
    intent: documents
spec:
  storageClassName: "ibmc-file-gold"
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fsf-mex0101c-fz.service.softlayer.com
    path: /IBM02SEV2071092_94328/data01/documents
