kind: PersistentVolume
apiVersion: v1
metadata:
  name: sterlingb2bitoolkit-pv
  labels:
    failure-domain.beta.kubernetes.io/region: us-south
    failure-domain.beta.kubernetes.io/zone: mex01
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fsf-mex0101c-fz.service.softlayer.com
    path: /IBM02SEV2071092_94328/data01
